version: '3'

services:
  app:
    build: ./
    command: ./app
    ports:
      - "8080:8080"
    depends_on:
      - user_repo
      - user_repo_cache

  user_repo:
    restart: always
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  user_repo_cache:
    restart: always
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  db-data:
