"server":
  "ginserver":
    "host": "app"
    "port": 8080

"userrepo":
  "postgres":
    "username": "postgres"
    "password": "postgres"
    "host": "user_repo"
    "port": "5432"
    "dbname": "postgres"
    "sslmode": "disable"
  
  "redis":
    "host": "user_repo_cache"
    "port": "6379"
    "password": ""
    "DB": 0
